USE BD_MENJUR_JOYAS_V2

--PROCEDIMIENTOS ALMACENADOS

CREATE PROCEDURE INGRESAR
@Usua VARCHAR (40),
@Cont VARCHAR (12)
AS
BEGIN
SELECT * FROM USUARIO WHERE Usuario=@Usua and Contrasena=@Cont
END
EXECUTE INGRESAR 'admin','1234'
GO
SELECT * FROM USUARIO