//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace BD_MENJUR_JOYASModel
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class BD_MENJUR_JOYASEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto BD_MENJUR_JOYASEntities usando la cadena de conexión encontrada en la sección 'BD_MENJUR_JOYASEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public BD_MENJUR_JOYASEntities() : base("name=BD_MENJUR_JOYASEntities", "BD_MENJUR_JOYASEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto BD_MENJUR_JOYASEntities.
        /// </summary>
        public BD_MENJUR_JOYASEntities(string connectionString) : base(connectionString, "BD_MENJUR_JOYASEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto BD_MENJUR_JOYASEntities.
        /// </summary>
        public BD_MENJUR_JOYASEntities(EntityConnection connection) : base(connection, "BD_MENJUR_JOYASEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Administradores> Administradores
        {
            get
            {
                if ((_Administradores == null))
                {
                    _Administradores = base.CreateObjectSet<Administradores>("Administradores");
                }
                return _Administradores;
            }
        }
        private ObjectSet<Administradores> _Administradores;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Clientes> Clientes
        {
            get
            {
                if ((_Clientes == null))
                {
                    _Clientes = base.CreateObjectSet<Clientes>("Clientes");
                }
                return _Clientes;
            }
        }
        private ObjectSet<Clientes> _Clientes;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Contacto> Contacto
        {
            get
            {
                if ((_Contacto == null))
                {
                    _Contacto = base.CreateObjectSet<Contacto>("Contacto");
                }
                return _Contacto;
            }
        }
        private ObjectSet<Contacto> _Contacto;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Factura> Factura
        {
            get
            {
                if ((_Factura == null))
                {
                    _Factura = base.CreateObjectSet<Factura>("Factura");
                }
                return _Factura;
            }
        }
        private ObjectSet<Factura> _Factura;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Producto> Producto
        {
            get
            {
                if ((_Producto == null))
                {
                    _Producto = base.CreateObjectSet<Producto>("Producto");
                }
                return _Producto;
            }
        }
        private ObjectSet<Producto> _Producto;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Administradores. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToAdministradores(Administradores administradores)
        {
            base.AddObject("Administradores", administradores);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Clientes. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToClientes(Clientes clientes)
        {
            base.AddObject("Clientes", clientes);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Contacto. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToContacto(Contacto contacto)
        {
            base.AddObject("Contacto", contacto);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Factura. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToFactura(Factura factura)
        {
            base.AddObject("Factura", factura);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Producto. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToProducto(Producto producto)
        {
            base.AddObject("Producto", producto);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_MENJUR_JOYASModel", Name="Administradores")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Administradores : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Administradores.
        /// </summary>
        /// <param name="iD_Administrador">Valor inicial de la propiedad ID_Administrador.</param>
        public static Administradores CreateAdministradores(global::System.Int32 iD_Administrador)
        {
            Administradores administradores = new Administradores();
            administradores.ID_Administrador = iD_Administrador;
            return administradores;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Administrador
        {
            get
            {
                return _ID_Administrador;
            }
            set
            {
                if (_ID_Administrador != value)
                {
                    OnID_AdministradorChanging(value);
                    ReportPropertyChanging("ID_Administrador");
                    _ID_Administrador = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_Administrador");
                    OnID_AdministradorChanged();
                }
            }
        }
        private global::System.Int32 _ID_Administrador;
        partial void OnID_AdministradorChanging(global::System.Int32 value);
        partial void OnID_AdministradorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NombresAdm
        {
            get
            {
                return _NombresAdm;
            }
            set
            {
                OnNombresAdmChanging(value);
                ReportPropertyChanging("NombresAdm");
                _NombresAdm = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NombresAdm");
                OnNombresAdmChanged();
            }
        }
        private global::System.String _NombresAdm;
        partial void OnNombresAdmChanging(global::System.String value);
        partial void OnNombresAdmChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ApellidosAdm
        {
            get
            {
                return _ApellidosAdm;
            }
            set
            {
                OnApellidosAdmChanging(value);
                ReportPropertyChanging("ApellidosAdm");
                _ApellidosAdm = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ApellidosAdm");
                OnApellidosAdmChanged();
            }
        }
        private global::System.String _ApellidosAdm;
        partial void OnApellidosAdmChanging(global::System.String value);
        partial void OnApellidosAdmChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Documento
        {
            get
            {
                return _Documento;
            }
            set
            {
                OnDocumentoChanging(value);
                ReportPropertyChanging("Documento");
                _Documento = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Documento");
                OnDocumentoChanged();
            }
        }
        private global::System.String _Documento;
        partial void OnDocumentoChanging(global::System.String value);
        partial void OnDocumentoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Dirección
        {
            get
            {
                return _Dirección;
            }
            set
            {
                OnDirecciónChanging(value);
                ReportPropertyChanging("Dirección");
                _Dirección = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Dirección");
                OnDirecciónChanged();
            }
        }
        private global::System.String _Dirección;
        partial void OnDirecciónChanging(global::System.String value);
        partial void OnDirecciónChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Teléfono
        {
            get
            {
                return _Teléfono;
            }
            set
            {
                OnTeléfonoChanging(value);
                ReportPropertyChanging("Teléfono");
                _Teléfono = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Teléfono");
                OnTeléfonoChanged();
            }
        }
        private global::System.String _Teléfono;
        partial void OnTeléfonoChanging(global::System.String value);
        partial void OnTeléfonoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Correo
        {
            get
            {
                return _Correo;
            }
            set
            {
                OnCorreoChanging(value);
                ReportPropertyChanging("Correo");
                _Correo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Correo");
                OnCorreoChanged();
            }
        }
        private global::System.String _Correo;
        partial void OnCorreoChanging(global::System.String value);
        partial void OnCorreoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Celular
        {
            get
            {
                return _Celular;
            }
            set
            {
                OnCelularChanging(value);
                ReportPropertyChanging("Celular");
                _Celular = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Celular");
                OnCelularChanged();
            }
        }
        private global::System.String _Celular;
        partial void OnCelularChanging(global::System.String value);
        partial void OnCelularChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ciudad
        {
            get
            {
                return _Ciudad;
            }
            set
            {
                OnCiudadChanging(value);
                ReportPropertyChanging("Ciudad");
                _Ciudad = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ciudad");
                OnCiudadChanged();
            }
        }
        private global::System.String _Ciudad;
        partial void OnCiudadChanging(global::System.String value);
        partial void OnCiudadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Usuario
        {
            get
            {
                return _Usuario;
            }
            set
            {
                OnUsuarioChanging(value);
                ReportPropertyChanging("Usuario");
                _Usuario = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Usuario");
                OnUsuarioChanged();
            }
        }
        private global::System.String _Usuario;
        partial void OnUsuarioChanging(global::System.String value);
        partial void OnUsuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Contraseña
        {
            get
            {
                return _Contraseña;
            }
            set
            {
                OnContraseñaChanging(value);
                ReportPropertyChanging("Contraseña");
                _Contraseña = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Contraseña");
                OnContraseñaChanged();
            }
        }
        private global::System.String _Contraseña;
        partial void OnContraseñaChanging(global::System.String value);
        partial void OnContraseñaChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_MENJUR_JOYASModel", Name="Clientes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Clientes : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Clientes.
        /// </summary>
        /// <param name="iD_Cliente">Valor inicial de la propiedad ID_Cliente.</param>
        public static Clientes CreateClientes(global::System.Int32 iD_Cliente)
        {
            Clientes clientes = new Clientes();
            clientes.ID_Cliente = iD_Cliente;
            return clientes;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Cliente
        {
            get
            {
                return _ID_Cliente;
            }
            set
            {
                if (_ID_Cliente != value)
                {
                    OnID_ClienteChanging(value);
                    ReportPropertyChanging("ID_Cliente");
                    _ID_Cliente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_Cliente");
                    OnID_ClienteChanged();
                }
            }
        }
        private global::System.Int32 _ID_Cliente;
        partial void OnID_ClienteChanging(global::System.Int32 value);
        partial void OnID_ClienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NombresCli
        {
            get
            {
                return _NombresCli;
            }
            set
            {
                OnNombresCliChanging(value);
                ReportPropertyChanging("NombresCli");
                _NombresCli = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NombresCli");
                OnNombresCliChanged();
            }
        }
        private global::System.String _NombresCli;
        partial void OnNombresCliChanging(global::System.String value);
        partial void OnNombresCliChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ApellidosCli
        {
            get
            {
                return _ApellidosCli;
            }
            set
            {
                OnApellidosCliChanging(value);
                ReportPropertyChanging("ApellidosCli");
                _ApellidosCli = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ApellidosCli");
                OnApellidosCliChanged();
            }
        }
        private global::System.String _ApellidosCli;
        partial void OnApellidosCliChanging(global::System.String value);
        partial void OnApellidosCliChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Documento
        {
            get
            {
                return _Documento;
            }
            set
            {
                OnDocumentoChanging(value);
                ReportPropertyChanging("Documento");
                _Documento = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Documento");
                OnDocumentoChanged();
            }
        }
        private global::System.String _Documento;
        partial void OnDocumentoChanging(global::System.String value);
        partial void OnDocumentoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Dirección
        {
            get
            {
                return _Dirección;
            }
            set
            {
                OnDirecciónChanging(value);
                ReportPropertyChanging("Dirección");
                _Dirección = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Dirección");
                OnDirecciónChanged();
            }
        }
        private global::System.String _Dirección;
        partial void OnDirecciónChanging(global::System.String value);
        partial void OnDirecciónChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Teléfono
        {
            get
            {
                return _Teléfono;
            }
            set
            {
                OnTeléfonoChanging(value);
                ReportPropertyChanging("Teléfono");
                _Teléfono = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Teléfono");
                OnTeléfonoChanged();
            }
        }
        private global::System.String _Teléfono;
        partial void OnTeléfonoChanging(global::System.String value);
        partial void OnTeléfonoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Correo
        {
            get
            {
                return _Correo;
            }
            set
            {
                OnCorreoChanging(value);
                ReportPropertyChanging("Correo");
                _Correo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Correo");
                OnCorreoChanged();
            }
        }
        private global::System.String _Correo;
        partial void OnCorreoChanging(global::System.String value);
        partial void OnCorreoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Celular
        {
            get
            {
                return _Celular;
            }
            set
            {
                OnCelularChanging(value);
                ReportPropertyChanging("Celular");
                _Celular = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Celular");
                OnCelularChanged();
            }
        }
        private global::System.String _Celular;
        partial void OnCelularChanging(global::System.String value);
        partial void OnCelularChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ciudad
        {
            get
            {
                return _Ciudad;
            }
            set
            {
                OnCiudadChanging(value);
                ReportPropertyChanging("Ciudad");
                _Ciudad = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ciudad");
                OnCiudadChanged();
            }
        }
        private global::System.String _Ciudad;
        partial void OnCiudadChanging(global::System.String value);
        partial void OnCiudadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Usuario
        {
            get
            {
                return _Usuario;
            }
            set
            {
                OnUsuarioChanging(value);
                ReportPropertyChanging("Usuario");
                _Usuario = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Usuario");
                OnUsuarioChanged();
            }
        }
        private global::System.String _Usuario;
        partial void OnUsuarioChanging(global::System.String value);
        partial void OnUsuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Contraseña
        {
            get
            {
                return _Contraseña;
            }
            set
            {
                OnContraseñaChanging(value);
                ReportPropertyChanging("Contraseña");
                _Contraseña = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Contraseña");
                OnContraseñaChanged();
            }
        }
        private global::System.String _Contraseña;
        partial void OnContraseñaChanging(global::System.String value);
        partial void OnContraseñaChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_MENJUR_JOYASModel", Name="Contacto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Contacto : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Contacto.
        /// </summary>
        /// <param name="iDContacto">Valor inicial de la propiedad IDContacto.</param>
        public static Contacto CreateContacto(global::System.Int32 iDContacto)
        {
            Contacto contacto = new Contacto();
            contacto.IDContacto = iDContacto;
            return contacto;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDContacto
        {
            get
            {
                return _IDContacto;
            }
            set
            {
                if (_IDContacto != value)
                {
                    OnIDContactoChanging(value);
                    ReportPropertyChanging("IDContacto");
                    _IDContacto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDContacto");
                    OnIDContactoChanged();
                }
            }
        }
        private global::System.Int32 _IDContacto;
        partial void OnIDContactoChanging(global::System.Int32 value);
        partial void OnIDContactoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NomContacto
        {
            get
            {
                return _NomContacto;
            }
            set
            {
                OnNomContactoChanging(value);
                ReportPropertyChanging("NomContacto");
                _NomContacto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NomContacto");
                OnNomContactoChanged();
            }
        }
        private global::System.String _NomContacto;
        partial void OnNomContactoChanging(global::System.String value);
        partial void OnNomContactoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailContacto
        {
            get
            {
                return _EmailContacto;
            }
            set
            {
                OnEmailContactoChanging(value);
                ReportPropertyChanging("EmailContacto");
                _EmailContacto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmailContacto");
                OnEmailContactoChanged();
            }
        }
        private global::System.String _EmailContacto;
        partial void OnEmailContactoChanging(global::System.String value);
        partial void OnEmailContactoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TelContacto
        {
            get
            {
                return _TelContacto;
            }
            set
            {
                OnTelContactoChanging(value);
                ReportPropertyChanging("TelContacto");
                _TelContacto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TelContacto");
                OnTelContactoChanged();
            }
        }
        private global::System.String _TelContacto;
        partial void OnTelContactoChanging(global::System.String value);
        partial void OnTelContactoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MensajeContacto
        {
            get
            {
                return _MensajeContacto;
            }
            set
            {
                OnMensajeContactoChanging(value);
                ReportPropertyChanging("MensajeContacto");
                _MensajeContacto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MensajeContacto");
                OnMensajeContactoChanged();
            }
        }
        private global::System.String _MensajeContacto;
        partial void OnMensajeContactoChanging(global::System.String value);
        partial void OnMensajeContactoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_MENJUR_JOYASModel", Name="Factura")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Factura : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Factura.
        /// </summary>
        /// <param name="iDFactura">Valor inicial de la propiedad IDFactura.</param>
        public static Factura CreateFactura(global::System.Int32 iDFactura)
        {
            Factura factura = new Factura();
            factura.IDFactura = iDFactura;
            return factura;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDFactura
        {
            get
            {
                return _IDFactura;
            }
            set
            {
                if (_IDFactura != value)
                {
                    OnIDFacturaChanging(value);
                    ReportPropertyChanging("IDFactura");
                    _IDFactura = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDFactura");
                    OnIDFacturaChanged();
                }
            }
        }
        private global::System.Int32 _IDFactura;
        partial void OnIDFacturaChanging(global::System.Int32 value);
        partial void OnIDFacturaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDAdministrador
        {
            get
            {
                return _IDAdministrador;
            }
            set
            {
                OnIDAdministradorChanging(value);
                ReportPropertyChanging("IDAdministrador");
                _IDAdministrador = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDAdministrador");
                OnIDAdministradorChanged();
            }
        }
        private Nullable<global::System.Int32> _IDAdministrador;
        partial void OnIDAdministradorChanging(Nullable<global::System.Int32> value);
        partial void OnIDAdministradorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private Nullable<global::System.DateTime> _Fecha;
        partial void OnFechaChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDCliente
        {
            get
            {
                return _IDCliente;
            }
            set
            {
                OnIDClienteChanging(value);
                ReportPropertyChanging("IDCliente");
                _IDCliente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDCliente");
                OnIDClienteChanged();
            }
        }
        private Nullable<global::System.Int32> _IDCliente;
        partial void OnIDClienteChanging(Nullable<global::System.Int32> value);
        partial void OnIDClienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDProducto
        {
            get
            {
                return _IDProducto;
            }
            set
            {
                OnIDProductoChanging(value);
                ReportPropertyChanging("IDProducto");
                _IDProducto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDProducto");
                OnIDProductoChanged();
            }
        }
        private Nullable<global::System.Int32> _IDProducto;
        partial void OnIDProductoChanging(Nullable<global::System.Int32> value);
        partial void OnIDProductoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Cantidad
        {
            get
            {
                return _Cantidad;
            }
            set
            {
                OnCantidadChanging(value);
                ReportPropertyChanging("Cantidad");
                _Cantidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cantidad");
                OnCantidadChanged();
            }
        }
        private Nullable<global::System.Int32> _Cantidad;
        partial void OnCantidadChanging(Nullable<global::System.Int32> value);
        partial void OnCantidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Total
        {
            get
            {
                return _Total;
            }
            set
            {
                OnTotalChanging(value);
                ReportPropertyChanging("Total");
                _Total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Total");
                OnTotalChanged();
            }
        }
        private Nullable<global::System.Int32> _Total;
        partial void OnTotalChanging(Nullable<global::System.Int32> value);
        partial void OnTotalChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_MENJUR_JOYASModel", Name="Producto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Producto : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Producto.
        /// </summary>
        /// <param name="iDProducto">Valor inicial de la propiedad IDProducto.</param>
        public static Producto CreateProducto(global::System.Int32 iDProducto)
        {
            Producto producto = new Producto();
            producto.IDProducto = iDProducto;
            return producto;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDProducto
        {
            get
            {
                return _IDProducto;
            }
            set
            {
                if (_IDProducto != value)
                {
                    OnIDProductoChanging(value);
                    ReportPropertyChanging("IDProducto");
                    _IDProducto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDProducto");
                    OnIDProductoChanged();
                }
            }
        }
        private global::System.Int32 _IDProducto;
        partial void OnIDProductoChanging(global::System.Int32 value);
        partial void OnIDProductoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NombrePro
        {
            get
            {
                return _NombrePro;
            }
            set
            {
                OnNombreProChanging(value);
                ReportPropertyChanging("NombrePro");
                _NombrePro = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NombrePro");
                OnNombreProChanged();
            }
        }
        private global::System.String _NombrePro;
        partial void OnNombreProChanging(global::System.String value);
        partial void OnNombreProChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CantidadPro
        {
            get
            {
                return _CantidadPro;
            }
            set
            {
                OnCantidadProChanging(value);
                ReportPropertyChanging("CantidadPro");
                _CantidadPro = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CantidadPro");
                OnCantidadProChanged();
            }
        }
        private global::System.String _CantidadPro;
        partial void OnCantidadProChanging(global::System.String value);
        partial void OnCantidadProChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Referencia
        {
            get
            {
                return _Referencia;
            }
            set
            {
                OnReferenciaChanging(value);
                ReportPropertyChanging("Referencia");
                _Referencia = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Referencia");
                OnReferenciaChanged();
            }
        }
        private global::System.String _Referencia;
        partial void OnReferenciaChanging(global::System.String value);
        partial void OnReferenciaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DescripcionPro
        {
            get
            {
                return _DescripcionPro;
            }
            set
            {
                OnDescripcionProChanging(value);
                ReportPropertyChanging("DescripcionPro");
                _DescripcionPro = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DescripcionPro");
                OnDescripcionProChanged();
            }
        }
        private global::System.String _DescripcionPro;
        partial void OnDescripcionProChanging(global::System.String value);
        partial void OnDescripcionProChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Peso
        {
            get
            {
                return _Peso;
            }
            set
            {
                OnPesoChanging(value);
                ReportPropertyChanging("Peso");
                _Peso = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Peso");
                OnPesoChanged();
            }
        }
        private global::System.String _Peso;
        partial void OnPesoChanging(global::System.String value);
        partial void OnPesoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> Precio
        {
            get
            {
                return _Precio;
            }
            set
            {
                OnPrecioChanging(value);
                ReportPropertyChanging("Precio");
                _Precio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Precio");
                OnPrecioChanged();
            }
        }
        private Nullable<global::System.Single> _Precio;
        partial void OnPrecioChanging(Nullable<global::System.Single> value);
        partial void OnPrecioChanged();

        #endregion

    
    }

    #endregion

    
}
